/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>

char findTheDifference1(char* s, char* t) {
    while(*(t+1)!='\0'){
    	char *tmp=strchr(s,*t);
    	if(!tmp) return *t;
    	else *tmp='1';
    	t=t+1;
    }
    return *t;
}

char findTheDifference(char* s, char* t) {
    int sum = 0;
    for (;*s != NULL && *t != NULL; s++, t++) {
        sum += *t - *s;
    }
    sum += *t;
    return sum;
}
int main(int argc, char const *argv[])
{
	char s[]="abca";
	char t[]="acbaa";
	printf("%c\n", findTheDifference(s,t));
	return 0;
}